/* Auto-generated by genmsg_cpp for file /home/reza/git/care-o-bot/cob_common/cob_msgs/msg/RectArray.msg */
#ifndef COB_MSGS_MESSAGE_RECTARRAY_H
#define COB_MSGS_MESSAGE_RECTARRAY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"
#include "cob_msgs/Rect.h"

namespace cob_msgs
{
template <class ContainerAllocator>
struct RectArray_ : public ros::Message
{
  typedef RectArray_<ContainerAllocator> Type;

  RectArray_()
  : header()
  , rects()
  {
  }

  RectArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , rects(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::cob_msgs::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cob_msgs::Rect_<ContainerAllocator> >::other >  _rects_type;
  std::vector< ::cob_msgs::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cob_msgs::Rect_<ContainerAllocator> >::other >  rects;


  ROS_DEPRECATED uint32_t get_rects_size() const { return (uint32_t)rects.size(); }
  ROS_DEPRECATED void set_rects_size(uint32_t size) { rects.resize((size_t)size); }
  ROS_DEPRECATED void get_rects_vec(std::vector< ::cob_msgs::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cob_msgs::Rect_<ContainerAllocator> >::other > & vec) const { vec = this->rects; }
  ROS_DEPRECATED void set_rects_vec(const std::vector< ::cob_msgs::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cob_msgs::Rect_<ContainerAllocator> >::other > & vec) { this->rects = vec; }
private:
  static const char* __s_getDataType_() { return "cob_msgs/RectArray"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e83b38fbaea3a641fa77f009f9bf492e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
Rect[] rects\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cob_msgs/Rect\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, rects);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, rects);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(rects);
    return size;
  }

  typedef boost::shared_ptr< ::cob_msgs::RectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_msgs::RectArray_<ContainerAllocator>  const> ConstPtr;
}; // struct RectArray
typedef  ::cob_msgs::RectArray_<std::allocator<void> > RectArray;

typedef boost::shared_ptr< ::cob_msgs::RectArray> RectArrayPtr;
typedef boost::shared_ptr< ::cob_msgs::RectArray const> RectArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cob_msgs::RectArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cob_msgs::RectArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cob_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::cob_msgs::RectArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e83b38fbaea3a641fa77f009f9bf492e";
  }

  static const char* value(const  ::cob_msgs::RectArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe83b38fbaea3a641ULL;
  static const uint64_t static_value2 = 0xfa77f009f9bf492eULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_msgs::RectArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_msgs/RectArray";
  }

  static const char* value(const  ::cob_msgs::RectArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_msgs::RectArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
Rect[] rects\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cob_msgs/Rect\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
\n\
";
  }

  static const char* value(const  ::cob_msgs::RectArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cob_msgs::RectArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cob_msgs::RectArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_msgs::RectArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.rects);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RectArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_msgs::RectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cob_msgs::RectArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rects[]" << std::endl;
    for (size_t i = 0; i < v.rects.size(); ++i)
    {
      s << indent << "  rects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cob_msgs::Rect_<ContainerAllocator> >::stream(s, indent + "    ", v.rects[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // COB_MSGS_MESSAGE_RECTARRAY_H

