/* Auto-generated by genmsg_cpp for file /home/reza/git/care-o-bot/cob_common/cob_msgs/msg/Transformation.msg */
#ifndef COB_MSGS_MESSAGE_TRANSFORMATION_H
#define COB_MSGS_MESSAGE_TRANSFORMATION_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace cob_msgs
{
template <class ContainerAllocator>
struct Transformation_ : public ros::Message
{
  typedef Transformation_<ContainerAllocator> Type;

  Transformation_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  Transformation_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;


private:
  static const char* __s_getDataType_() { return "cob_msgs/Transformation"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1a83f0bdabe750ce0cfb45a14ec63457"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#message for exchanging transformations in x,y,z positions and roll, pitch, yaw angles\n\
\n\
#std_msgs/Header header\n\
\n\
#translation\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
#rotation\n\
float64 roll #roll\n\
float64 pitch #pitch\n\
float64 yaw #yaw\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, z);
    ros::serialization::serialize(stream, roll);
    ros::serialization::serialize(stream, pitch);
    ros::serialization::serialize(stream, yaw);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, z);
    ros::serialization::deserialize(stream, roll);
    ros::serialization::deserialize(stream, pitch);
    ros::serialization::deserialize(stream, yaw);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(z);
    size += ros::serialization::serializationLength(roll);
    size += ros::serialization::serializationLength(pitch);
    size += ros::serialization::serializationLength(yaw);
    return size;
  }

  typedef boost::shared_ptr< ::cob_msgs::Transformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_msgs::Transformation_<ContainerAllocator>  const> ConstPtr;
}; // struct Transformation
typedef  ::cob_msgs::Transformation_<std::allocator<void> > Transformation;

typedef boost::shared_ptr< ::cob_msgs::Transformation> TransformationPtr;
typedef boost::shared_ptr< ::cob_msgs::Transformation const> TransformationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cob_msgs::Transformation_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cob_msgs::Transformation_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cob_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::cob_msgs::Transformation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a83f0bdabe750ce0cfb45a14ec63457";
  }

  static const char* value(const  ::cob_msgs::Transformation_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1a83f0bdabe750ceULL;
  static const uint64_t static_value2 = 0x0cfb45a14ec63457ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_msgs::Transformation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_msgs/Transformation";
  }

  static const char* value(const  ::cob_msgs::Transformation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_msgs::Transformation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#message for exchanging transformations in x,y,z positions and roll, pitch, yaw angles\n\
\n\
#std_msgs/Header header\n\
\n\
#translation\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
#rotation\n\
float64 roll #roll\n\
float64 pitch #pitch\n\
float64 yaw #yaw\n\
\n\
";
  }

  static const char* value(const  ::cob_msgs::Transformation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cob_msgs::Transformation_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_msgs::Transformation_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Transformation_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_msgs::Transformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cob_msgs::Transformation_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COB_MSGS_MESSAGE_TRANSFORMATION_H

