/* Auto-generated by genmsg_cpp for file /home/reza/git/care-o-bot/cob_common/cob_srvs/srv/Trigger.srv */
#ifndef COB_SRVS_SERVICE_TRIGGER_H
#define COB_SRVS_SERVICE_TRIGGER_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"



#include "std_msgs/Bool.h"
#include "std_msgs/String.h"

namespace cob_srvs
{
template <class ContainerAllocator>
struct TriggerRequest_ : public ros::Message
{
  typedef TriggerRequest_<ContainerAllocator> Type;

  TriggerRequest_()
  {
  }

  TriggerRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "cob_srvs/TriggerRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "bdad515e8f4c013bd650d3407753d2b8"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::cob_srvs::TriggerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_srvs::TriggerRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct TriggerRequest
typedef  ::cob_srvs::TriggerRequest_<std::allocator<void> > TriggerRequest;

typedef boost::shared_ptr< ::cob_srvs::TriggerRequest> TriggerRequestPtr;
typedef boost::shared_ptr< ::cob_srvs::TriggerRequest const> TriggerRequestConstPtr;


template <class ContainerAllocator>
struct TriggerResponse_ : public ros::Message
{
  typedef TriggerResponse_<ContainerAllocator> Type;

  TriggerResponse_()
  : success()
  , error_message()
  {
  }

  TriggerResponse_(const ContainerAllocator& _alloc)
  : success(_alloc)
  , error_message(_alloc)
  {
  }

  typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
   ::std_msgs::Bool_<ContainerAllocator>  success;

  typedef  ::std_msgs::String_<ContainerAllocator>  _error_message_type;
   ::std_msgs::String_<ContainerAllocator>  error_message;


private:
  static const char* __s_getDataType_() { return "cob_srvs/TriggerResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "bdad515e8f4c013bd650d3407753d2b8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "bdad515e8f4c013bd650d3407753d2b8"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "std_msgs/Bool success\n\
std_msgs/String error_message\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    ros::serialization::serialize(stream, error_message);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    ros::serialization::deserialize(stream, error_message);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    size += ros::serialization::serializationLength(error_message);
    return size;
  }

  typedef boost::shared_ptr< ::cob_srvs::TriggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_srvs::TriggerResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct TriggerResponse
typedef  ::cob_srvs::TriggerResponse_<std::allocator<void> > TriggerResponse;

typedef boost::shared_ptr< ::cob_srvs::TriggerResponse> TriggerResponsePtr;
typedef boost::shared_ptr< ::cob_srvs::TriggerResponse const> TriggerResponseConstPtr;

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Trigger
} // namespace cob_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::cob_srvs::TriggerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::cob_srvs::TriggerRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_srvs::TriggerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_srvs/TriggerRequest";
  }

  static const char* value(const  ::cob_srvs::TriggerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_srvs::TriggerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::cob_srvs::TriggerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cob_srvs::TriggerRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::cob_srvs::TriggerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bdad515e8f4c013bd650d3407753d2b8";
  }

  static const char* value(const  ::cob_srvs::TriggerResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbdad515e8f4c013bULL;
  static const uint64_t static_value2 = 0xd650d3407753d2b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_srvs::TriggerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_srvs/TriggerResponse";
  }

  static const char* value(const  ::cob_srvs::TriggerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_srvs::TriggerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Bool success\n\
std_msgs/String error_message\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
";
  }

  static const char* value(const  ::cob_srvs::TriggerResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_srvs::TriggerRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TriggerRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_srvs::TriggerResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
    stream.next(m.error_message);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TriggerResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<cob_srvs::Trigger> {
  static const char* value() 
  {
    return "bdad515e8f4c013bd650d3407753d2b8";
  }

  static const char* value(const cob_srvs::Trigger&) { return value(); } 
};

template<>
struct DataType<cob_srvs::Trigger> {
  static const char* value() 
  {
    return "cob_srvs/Trigger";
  }

  static const char* value(const cob_srvs::Trigger&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<cob_srvs::TriggerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bdad515e8f4c013bd650d3407753d2b8";
  }

  static const char* value(const cob_srvs::TriggerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<cob_srvs::TriggerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_srvs/Trigger";
  }

  static const char* value(const cob_srvs::TriggerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<cob_srvs::TriggerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bdad515e8f4c013bd650d3407753d2b8";
  }

  static const char* value(const cob_srvs::TriggerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<cob_srvs::TriggerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_srvs/Trigger";
  }

  static const char* value(const cob_srvs::TriggerResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_SERVICE_TRIGGER_H

