/* Auto-generated by genmsg_cpp for file /home/reza/git/care-o-bot/cob_apps/cob_script_server/msg/StateGoal.msg */
#ifndef COB_SCRIPT_SERVER_MESSAGE_STATEGOAL_H
#define COB_SCRIPT_SERVER_MESSAGE_STATEGOAL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "cob_script_server/ScriptState.h"

namespace cob_script_server
{
template <class ContainerAllocator>
struct StateGoal_ : public ros::Message
{
  typedef StateGoal_<ContainerAllocator> Type;

  StateGoal_()
  : state()
  {
  }

  StateGoal_(const ContainerAllocator& _alloc)
  : state(_alloc)
  {
  }

  typedef  ::cob_script_server::ScriptState_<ContainerAllocator>  _state_type;
   ::cob_script_server::ScriptState_<ContainerAllocator>  state;


private:
  static const char* __s_getDataType_() { return "cob_script_server/StateGoal"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5d2b1a5f7b8263c9eb024ed31a5dbee9"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
cob_script_server/ScriptState state\n\
\n\
================================================================================\n\
MSG: cob_script_server/ScriptState\n\
Header header\n\
int16 number\n\
string function_name\n\
string component_name\n\
string parameter_name\n\
string full_graph_name\n\
\n\
# Possible execution states\n\
byte UNKNOWN=0\n\
byte ACTIVE=1\n\
byte SUCCEEDED=2\n\
byte FAILED=3\n\
byte PAUSED=4\n\
\n\
byte state # state of execution\n\
int16 error_code # current error_code for state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(state);
    return size;
  }

  typedef boost::shared_ptr< ::cob_script_server::StateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_script_server::StateGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct StateGoal
typedef  ::cob_script_server::StateGoal_<std::allocator<void> > StateGoal;

typedef boost::shared_ptr< ::cob_script_server::StateGoal> StateGoalPtr;
typedef boost::shared_ptr< ::cob_script_server::StateGoal const> StateGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cob_script_server::StateGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cob_script_server::StateGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cob_script_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::cob_script_server::StateGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d2b1a5f7b8263c9eb024ed31a5dbee9";
  }

  static const char* value(const  ::cob_script_server::StateGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5d2b1a5f7b8263c9ULL;
  static const uint64_t static_value2 = 0xeb024ed31a5dbee9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_script_server::StateGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_script_server/StateGoal";
  }

  static const char* value(const  ::cob_script_server::StateGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_script_server::StateGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
cob_script_server/ScriptState state\n\
\n\
================================================================================\n\
MSG: cob_script_server/ScriptState\n\
Header header\n\
int16 number\n\
string function_name\n\
string component_name\n\
string parameter_name\n\
string full_graph_name\n\
\n\
# Possible execution states\n\
byte UNKNOWN=0\n\
byte ACTIVE=1\n\
byte SUCCEEDED=2\n\
byte FAILED=3\n\
byte PAUSED=4\n\
\n\
byte state # state of execution\n\
int16 error_code # current error_code for state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cob_script_server::StateGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_script_server::StateGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StateGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_script_server::StateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cob_script_server::StateGoal_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
s << std::endl;
    Printer< ::cob_script_server::ScriptState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COB_SCRIPT_SERVER_MESSAGE_STATEGOAL_H

